/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { FAAssetList } from '../models';
// @ts-ignore
import { PagedFAAssetList } from '../models';
/**
 * FAAssetListApi - axios parameter creator
 * @export
 */
export const FAAssetListApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} assetCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fAAssetListAssetCodeGet: async (assetCode: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'assetCode' is not null or undefined
            assertParamExists('fAAssetListAssetCodeGet', 'assetCode', assetCode)
            const localVarPath = `/FAAssetList('{AssetCode}')`
                .replace(`{${"AssetCode"}}`, encodeURIComponent(String(assetCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fAAssetListGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/FAAssetList`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FAAssetListApi - functional programming interface
 * @export
 */
export const FAAssetListApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FAAssetListApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} assetCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fAAssetListAssetCodeGet(assetCode: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FAAssetList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fAAssetListAssetCodeGet(assetCode, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fAAssetListGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedFAAssetList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fAAssetListGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FAAssetListApi - factory interface
 * @export
 */
export const FAAssetListApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FAAssetListApiFp(configuration)
    return {
        /**
         * 
         * @param {string} assetCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fAAssetListAssetCodeGet(assetCode: string, options?: any): AxiosPromise<FAAssetList> {
            return localVarFp.fAAssetListAssetCodeGet(assetCode, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fAAssetListGet(options?: any): AxiosPromise<PagedFAAssetList> {
            return localVarFp.fAAssetListGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FAAssetListApi - interface
 * @export
 * @interface FAAssetListApi
 */
export interface FAAssetListApiInterface {
    /**
     * 
     * @param {string} assetCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FAAssetListApiInterface
     */
    fAAssetListAssetCodeGet(assetCode: string, options?: AxiosRequestConfig): AxiosPromise<FAAssetList>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FAAssetListApiInterface
     */
    fAAssetListGet(options?: AxiosRequestConfig): AxiosPromise<PagedFAAssetList>;

}

/**
 * FAAssetListApi - object-oriented interface
 * @export
 * @class FAAssetListApi
 * @extends {BaseAPI}
 */
export class FAAssetListApi extends BaseAPI implements FAAssetListApiInterface {
    /**
     * 
     * @param {string} assetCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FAAssetListApi
     */
    public fAAssetListAssetCodeGet(assetCode: string, options?: AxiosRequestConfig) {
        return FAAssetListApiFp(this.configuration).fAAssetListAssetCodeGet(assetCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FAAssetListApi
     */
    public fAAssetListGet(options?: AxiosRequestConfig) {
        return FAAssetListApiFp(this.configuration).fAAssetListGet(options).then((request) => request(this.axios, this.basePath));
    }
}
