/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PagedTABLECOBIND } from '../models';
// @ts-ignore
import { TABLECOBIND } from '../models';
/**
 * TABLECOBINDApi - axios parameter creator
 * @export
 */
export const TABLECOBINDApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} bindID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLECOBINDBindIDGet: async (bindID: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bindID' is not null or undefined
            assertParamExists('tABLECOBINDBindIDGet', 'bindID', bindID)
            const localVarPath = `/TABLE_COBIND('{BindID}')`
                .replace(`{${"BindID"}}`, encodeURIComponent(String(bindID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLECOBINDGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/TABLE_COBIND`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TABLECOBINDApi - functional programming interface
 * @export
 */
export const TABLECOBINDApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TABLECOBINDApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} bindID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLECOBINDBindIDGet(bindID: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TABLECOBIND>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLECOBINDBindIDGet(bindID, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLECOBINDGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedTABLECOBIND>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLECOBINDGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TABLECOBINDApi - factory interface
 * @export
 */
export const TABLECOBINDApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TABLECOBINDApiFp(configuration)
    return {
        /**
         * 
         * @param {number} bindID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLECOBINDBindIDGet(bindID: number, options?: any): AxiosPromise<TABLECOBIND> {
            return localVarFp.tABLECOBINDBindIDGet(bindID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLECOBINDGet(options?: any): AxiosPromise<PagedTABLECOBIND> {
            return localVarFp.tABLECOBINDGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TABLECOBINDApi - interface
 * @export
 * @interface TABLECOBINDApi
 */
export interface TABLECOBINDApiInterface {
    /**
     * 
     * @param {number} bindID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLECOBINDApiInterface
     */
    tABLECOBINDBindIDGet(bindID: number, options?: AxiosRequestConfig): AxiosPromise<TABLECOBIND>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLECOBINDApiInterface
     */
    tABLECOBINDGet(options?: AxiosRequestConfig): AxiosPromise<PagedTABLECOBIND>;

}

/**
 * TABLECOBINDApi - object-oriented interface
 * @export
 * @class TABLECOBINDApi
 * @extends {BaseAPI}
 */
export class TABLECOBINDApi extends BaseAPI implements TABLECOBINDApiInterface {
    /**
     * 
     * @param {number} bindID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLECOBINDApi
     */
    public tABLECOBINDBindIDGet(bindID: number, options?: AxiosRequestConfig) {
        return TABLECOBINDApiFp(this.configuration).tABLECOBINDBindIDGet(bindID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLECOBINDApi
     */
    public tABLECOBINDGet(options?: AxiosRequestConfig) {
        return TABLECOBINDApiFp(this.configuration).tABLECOBINDGet(options).then((request) => request(this.axios, this.basePath));
    }
}
