/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PagedTABLEJCBAL } from '../models';
// @ts-ignore
import { TABLEJCBAL } from '../models';
/**
 * TABLEJCBALApi - axios parameter creator
 * @export
 */
export const TABLEJCBALApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEJCBALGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/TABLE_JCBAL`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} jobCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEJCBALJobCodeGet: async (jobCode: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobCode' is not null or undefined
            assertParamExists('tABLEJCBALJobCodeGet', 'jobCode', jobCode)
            const localVarPath = `/TABLE_JCBAL('{JobCode}')`
                .replace(`{${"JobCode"}}`, encodeURIComponent(String(jobCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TABLEJCBALApi - functional programming interface
 * @export
 */
export const TABLEJCBALApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TABLEJCBALApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEJCBALGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedTABLEJCBAL>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEJCBALGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} jobCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEJCBALJobCodeGet(jobCode: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TABLEJCBAL>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEJCBALJobCodeGet(jobCode, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TABLEJCBALApi - factory interface
 * @export
 */
export const TABLEJCBALApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TABLEJCBALApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEJCBALGet(options?: any): AxiosPromise<PagedTABLEJCBAL> {
            return localVarFp.tABLEJCBALGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} jobCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEJCBALJobCodeGet(jobCode: string, options?: any): AxiosPromise<TABLEJCBAL> {
            return localVarFp.tABLEJCBALJobCodeGet(jobCode, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TABLEJCBALApi - interface
 * @export
 * @interface TABLEJCBALApi
 */
export interface TABLEJCBALApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEJCBALApiInterface
     */
    tABLEJCBALGet(options?: AxiosRequestConfig): AxiosPromise<PagedTABLEJCBAL>;

    /**
     * 
     * @param {string} jobCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEJCBALApiInterface
     */
    tABLEJCBALJobCodeGet(jobCode: string, options?: AxiosRequestConfig): AxiosPromise<TABLEJCBAL>;

}

/**
 * TABLEJCBALApi - object-oriented interface
 * @export
 * @class TABLEJCBALApi
 * @extends {BaseAPI}
 */
export class TABLEJCBALApi extends BaseAPI implements TABLEJCBALApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEJCBALApi
     */
    public tABLEJCBALGet(options?: AxiosRequestConfig) {
        return TABLEJCBALApiFp(this.configuration).tABLEJCBALGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} jobCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEJCBALApi
     */
    public tABLEJCBALJobCodeGet(jobCode: string, options?: AxiosRequestConfig) {
        return TABLEJCBALApiFp(this.configuration).tABLEJCBALJobCodeGet(jobCode, options).then((request) => request(this.axios, this.basePath));
    }
}
