/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PagedTABLEGSTTRAN } from '../models';
// @ts-ignore
import { TABLEGSTTRAN } from '../models';
/**
 * TABLEGSTTRANApi - axios parameter creator
 * @export
 */
export const TABLEGSTTRANApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEGSTTRANGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/TABLE_GSTTRAN`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} transactionID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEGSTTRANTransactionIDGet: async (transactionID: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'transactionID' is not null or undefined
            assertParamExists('tABLEGSTTRANTransactionIDGet', 'transactionID', transactionID)
            const localVarPath = `/TABLE_GSTTRAN('{TransactionID}')`
                .replace(`{${"TransactionID"}}`, encodeURIComponent(String(transactionID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TABLEGSTTRANApi - functional programming interface
 * @export
 */
export const TABLEGSTTRANApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TABLEGSTTRANApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEGSTTRANGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedTABLEGSTTRAN>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEGSTTRANGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} transactionID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEGSTTRANTransactionIDGet(transactionID: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TABLEGSTTRAN>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEGSTTRANTransactionIDGet(transactionID, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TABLEGSTTRANApi - factory interface
 * @export
 */
export const TABLEGSTTRANApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TABLEGSTTRANApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEGSTTRANGet(options?: any): AxiosPromise<PagedTABLEGSTTRAN> {
            return localVarFp.tABLEGSTTRANGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} transactionID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEGSTTRANTransactionIDGet(transactionID: number, options?: any): AxiosPromise<TABLEGSTTRAN> {
            return localVarFp.tABLEGSTTRANTransactionIDGet(transactionID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TABLEGSTTRANApi - interface
 * @export
 * @interface TABLEGSTTRANApi
 */
export interface TABLEGSTTRANApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEGSTTRANApiInterface
     */
    tABLEGSTTRANGet(options?: AxiosRequestConfig): AxiosPromise<PagedTABLEGSTTRAN>;

    /**
     * 
     * @param {number} transactionID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEGSTTRANApiInterface
     */
    tABLEGSTTRANTransactionIDGet(transactionID: number, options?: AxiosRequestConfig): AxiosPromise<TABLEGSTTRAN>;

}

/**
 * TABLEGSTTRANApi - object-oriented interface
 * @export
 * @class TABLEGSTTRANApi
 * @extends {BaseAPI}
 */
export class TABLEGSTTRANApi extends BaseAPI implements TABLEGSTTRANApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEGSTTRANApi
     */
    public tABLEGSTTRANGet(options?: AxiosRequestConfig) {
        return TABLEGSTTRANApiFp(this.configuration).tABLEGSTTRANGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} transactionID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEGSTTRANApi
     */
    public tABLEGSTTRANTransactionIDGet(transactionID: number, options?: AxiosRequestConfig) {
        return TABLEGSTTRANApiFp(this.configuration).tABLEGSTTRANTransactionIDGet(transactionID, options).then((request) => request(this.axios, this.basePath));
    }
}
