/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PagedTABLECOADDR } from '../models';
// @ts-ignore
import { TABLECOADDR } from '../models';
/**
 * TABLECOADDRApi - axios parameter creator
 * @export
 */
export const TABLECOADDRApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} deliveryCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLECOADDRDeliveryCodeGet: async (deliveryCode: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deliveryCode' is not null or undefined
            assertParamExists('tABLECOADDRDeliveryCodeGet', 'deliveryCode', deliveryCode)
            const localVarPath = `/TABLE_COADDR('{DeliveryCode}')`
                .replace(`{${"DeliveryCode"}}`, encodeURIComponent(String(deliveryCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLECOADDRGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/TABLE_COADDR`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TABLECOADDRApi - functional programming interface
 * @export
 */
export const TABLECOADDRApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TABLECOADDRApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} deliveryCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLECOADDRDeliveryCodeGet(deliveryCode: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TABLECOADDR>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLECOADDRDeliveryCodeGet(deliveryCode, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLECOADDRGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedTABLECOADDR>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLECOADDRGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TABLECOADDRApi - factory interface
 * @export
 */
export const TABLECOADDRApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TABLECOADDRApiFp(configuration)
    return {
        /**
         * 
         * @param {string} deliveryCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLECOADDRDeliveryCodeGet(deliveryCode: string, options?: any): AxiosPromise<TABLECOADDR> {
            return localVarFp.tABLECOADDRDeliveryCodeGet(deliveryCode, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLECOADDRGet(options?: any): AxiosPromise<PagedTABLECOADDR> {
            return localVarFp.tABLECOADDRGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TABLECOADDRApi - interface
 * @export
 * @interface TABLECOADDRApi
 */
export interface TABLECOADDRApiInterface {
    /**
     * 
     * @param {string} deliveryCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLECOADDRApiInterface
     */
    tABLECOADDRDeliveryCodeGet(deliveryCode: string, options?: AxiosRequestConfig): AxiosPromise<TABLECOADDR>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLECOADDRApiInterface
     */
    tABLECOADDRGet(options?: AxiosRequestConfig): AxiosPromise<PagedTABLECOADDR>;

}

/**
 * TABLECOADDRApi - object-oriented interface
 * @export
 * @class TABLECOADDRApi
 * @extends {BaseAPI}
 */
export class TABLECOADDRApi extends BaseAPI implements TABLECOADDRApiInterface {
    /**
     * 
     * @param {string} deliveryCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLECOADDRApi
     */
    public tABLECOADDRDeliveryCodeGet(deliveryCode: string, options?: AxiosRequestConfig) {
        return TABLECOADDRApiFp(this.configuration).tABLECOADDRDeliveryCodeGet(deliveryCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLECOADDRApi
     */
    public tABLECOADDRGet(options?: AxiosRequestConfig) {
        return TABLECOADDRApiFp(this.configuration).tABLECOADDRGet(options).then((request) => request(this.axios, this.basePath));
    }
}
