/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PagedTABLEINSHIPLI } from '../models';
// @ts-ignore
import { TABLEINSHIPLI } from '../models';
/**
 * TABLEINSHIPLIApi - axios parameter creator
 * @export
 */
export const TABLEINSHIPLIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEINSHIPLIGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/TABLE_INSHIPLI`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} lineID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEINSHIPLILineIDGet: async (lineID: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'lineID' is not null or undefined
            assertParamExists('tABLEINSHIPLILineIDGet', 'lineID', lineID)
            const localVarPath = `/TABLE_INSHIPLI('{LineID}')`
                .replace(`{${"LineID"}}`, encodeURIComponent(String(lineID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TABLEINSHIPLIApi - functional programming interface
 * @export
 */
export const TABLEINSHIPLIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TABLEINSHIPLIApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEINSHIPLIGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedTABLEINSHIPLI>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEINSHIPLIGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} lineID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEINSHIPLILineIDGet(lineID: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TABLEINSHIPLI>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEINSHIPLILineIDGet(lineID, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TABLEINSHIPLIApi - factory interface
 * @export
 */
export const TABLEINSHIPLIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TABLEINSHIPLIApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEINSHIPLIGet(options?: any): AxiosPromise<PagedTABLEINSHIPLI> {
            return localVarFp.tABLEINSHIPLIGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} lineID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEINSHIPLILineIDGet(lineID: number, options?: any): AxiosPromise<TABLEINSHIPLI> {
            return localVarFp.tABLEINSHIPLILineIDGet(lineID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TABLEINSHIPLIApi - interface
 * @export
 * @interface TABLEINSHIPLIApi
 */
export interface TABLEINSHIPLIApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEINSHIPLIApiInterface
     */
    tABLEINSHIPLIGet(options?: AxiosRequestConfig): AxiosPromise<PagedTABLEINSHIPLI>;

    /**
     * 
     * @param {number} lineID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEINSHIPLIApiInterface
     */
    tABLEINSHIPLILineIDGet(lineID: number, options?: AxiosRequestConfig): AxiosPromise<TABLEINSHIPLI>;

}

/**
 * TABLEINSHIPLIApi - object-oriented interface
 * @export
 * @class TABLEINSHIPLIApi
 * @extends {BaseAPI}
 */
export class TABLEINSHIPLIApi extends BaseAPI implements TABLEINSHIPLIApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEINSHIPLIApi
     */
    public tABLEINSHIPLIGet(options?: AxiosRequestConfig) {
        return TABLEINSHIPLIApiFp(this.configuration).tABLEINSHIPLIGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} lineID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEINSHIPLIApi
     */
    public tABLEINSHIPLILineIDGet(lineID: number, options?: AxiosRequestConfig) {
        return TABLEINSHIPLIApiFp(this.configuration).tABLEINSHIPLILineIDGet(lineID, options).then((request) => request(this.axios, this.basePath));
    }
}
