/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PagedTABLEFABOOK } from '../models';
// @ts-ignore
import { TABLEFABOOK } from '../models';
/**
 * TABLEFABOOKApi - axios parameter creator
 * @export
 */
export const TABLEFABOOKApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} bookCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEFABOOKBookCodeGet: async (bookCode: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bookCode' is not null or undefined
            assertParamExists('tABLEFABOOKBookCodeGet', 'bookCode', bookCode)
            const localVarPath = `/TABLE_FABOOK('{BookCode}')`
                .replace(`{${"BookCode"}}`, encodeURIComponent(String(bookCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEFABOOKGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/TABLE_FABOOK`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TABLEFABOOKApi - functional programming interface
 * @export
 */
export const TABLEFABOOKApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TABLEFABOOKApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} bookCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEFABOOKBookCodeGet(bookCode: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TABLEFABOOK>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEFABOOKBookCodeGet(bookCode, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEFABOOKGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedTABLEFABOOK>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEFABOOKGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TABLEFABOOKApi - factory interface
 * @export
 */
export const TABLEFABOOKApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TABLEFABOOKApiFp(configuration)
    return {
        /**
         * 
         * @param {string} bookCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEFABOOKBookCodeGet(bookCode: string, options?: any): AxiosPromise<TABLEFABOOK> {
            return localVarFp.tABLEFABOOKBookCodeGet(bookCode, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEFABOOKGet(options?: any): AxiosPromise<PagedTABLEFABOOK> {
            return localVarFp.tABLEFABOOKGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TABLEFABOOKApi - interface
 * @export
 * @interface TABLEFABOOKApi
 */
export interface TABLEFABOOKApiInterface {
    /**
     * 
     * @param {string} bookCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEFABOOKApiInterface
     */
    tABLEFABOOKBookCodeGet(bookCode: string, options?: AxiosRequestConfig): AxiosPromise<TABLEFABOOK>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEFABOOKApiInterface
     */
    tABLEFABOOKGet(options?: AxiosRequestConfig): AxiosPromise<PagedTABLEFABOOK>;

}

/**
 * TABLEFABOOKApi - object-oriented interface
 * @export
 * @class TABLEFABOOKApi
 * @extends {BaseAPI}
 */
export class TABLEFABOOKApi extends BaseAPI implements TABLEFABOOKApiInterface {
    /**
     * 
     * @param {string} bookCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEFABOOKApi
     */
    public tABLEFABOOKBookCodeGet(bookCode: string, options?: AxiosRequestConfig) {
        return TABLEFABOOKApiFp(this.configuration).tABLEFABOOKBookCodeGet(bookCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEFABOOKApi
     */
    public tABLEFABOOKGet(options?: AxiosRequestConfig) {
        return TABLEFABOOKApiFp(this.configuration).tABLEFABOOKGet(options).then((request) => request(this.axios, this.basePath));
    }
}
