/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PagedTABLEAPBAL } from '../models';
// @ts-ignore
import { TABLEAPBAL } from '../models';
/**
 * TABLEAPBALApi - axios parameter creator
 * @export
 */
export const TABLEAPBALApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} creditorCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEAPBALCreditorCodeGet: async (creditorCode: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'creditorCode' is not null or undefined
            assertParamExists('tABLEAPBALCreditorCodeGet', 'creditorCode', creditorCode)
            const localVarPath = `/TABLE_APBAL('{CreditorCode}')`
                .replace(`{${"CreditorCode"}}`, encodeURIComponent(String(creditorCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEAPBALGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/TABLE_APBAL`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TABLEAPBALApi - functional programming interface
 * @export
 */
export const TABLEAPBALApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TABLEAPBALApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} creditorCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEAPBALCreditorCodeGet(creditorCode: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TABLEAPBAL>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEAPBALCreditorCodeGet(creditorCode, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEAPBALGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedTABLEAPBAL>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEAPBALGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TABLEAPBALApi - factory interface
 * @export
 */
export const TABLEAPBALApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TABLEAPBALApiFp(configuration)
    return {
        /**
         * 
         * @param {string} creditorCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEAPBALCreditorCodeGet(creditorCode: string, options?: any): AxiosPromise<TABLEAPBAL> {
            return localVarFp.tABLEAPBALCreditorCodeGet(creditorCode, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEAPBALGet(options?: any): AxiosPromise<PagedTABLEAPBAL> {
            return localVarFp.tABLEAPBALGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TABLEAPBALApi - interface
 * @export
 * @interface TABLEAPBALApi
 */
export interface TABLEAPBALApiInterface {
    /**
     * 
     * @param {string} creditorCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEAPBALApiInterface
     */
    tABLEAPBALCreditorCodeGet(creditorCode: string, options?: AxiosRequestConfig): AxiosPromise<TABLEAPBAL>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEAPBALApiInterface
     */
    tABLEAPBALGet(options?: AxiosRequestConfig): AxiosPromise<PagedTABLEAPBAL>;

}

/**
 * TABLEAPBALApi - object-oriented interface
 * @export
 * @class TABLEAPBALApi
 * @extends {BaseAPI}
 */
export class TABLEAPBALApi extends BaseAPI implements TABLEAPBALApiInterface {
    /**
     * 
     * @param {string} creditorCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEAPBALApi
     */
    public tABLEAPBALCreditorCodeGet(creditorCode: string, options?: AxiosRequestConfig) {
        return TABLEAPBALApiFp(this.configuration).tABLEAPBALCreditorCodeGet(creditorCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEAPBALApi
     */
    public tABLEAPBALGet(options?: AxiosRequestConfig) {
        return TABLEAPBALApiFp(this.configuration).tABLEAPBALGet(options).then((request) => request(this.axios, this.basePath));
    }
}
