/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PagedTABLEJCCTRL } from '../models';
// @ts-ignore
import { TABLEJCCTRL } from '../models';
/**
 * TABLEJCCTRLApi - axios parameter creator
 * @export
 */
export const TABLEJCCTRLApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEJCCTRLGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/TABLE_JCCTRL`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEJCCTRLUserCodeGet: async (userCode: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userCode' is not null or undefined
            assertParamExists('tABLEJCCTRLUserCodeGet', 'userCode', userCode)
            const localVarPath = `/TABLE_JCCTRL('{UserCode}')`
                .replace(`{${"UserCode"}}`, encodeURIComponent(String(userCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TABLEJCCTRLApi - functional programming interface
 * @export
 */
export const TABLEJCCTRLApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TABLEJCCTRLApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEJCCTRLGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedTABLEJCCTRL>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEJCCTRLGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} userCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEJCCTRLUserCodeGet(userCode: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TABLEJCCTRL>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEJCCTRLUserCodeGet(userCode, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TABLEJCCTRLApi - factory interface
 * @export
 */
export const TABLEJCCTRLApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TABLEJCCTRLApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEJCCTRLGet(options?: any): AxiosPromise<PagedTABLEJCCTRL> {
            return localVarFp.tABLEJCCTRLGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} userCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEJCCTRLUserCodeGet(userCode: string, options?: any): AxiosPromise<TABLEJCCTRL> {
            return localVarFp.tABLEJCCTRLUserCodeGet(userCode, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TABLEJCCTRLApi - interface
 * @export
 * @interface TABLEJCCTRLApi
 */
export interface TABLEJCCTRLApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEJCCTRLApiInterface
     */
    tABLEJCCTRLGet(options?: AxiosRequestConfig): AxiosPromise<PagedTABLEJCCTRL>;

    /**
     * 
     * @param {string} userCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEJCCTRLApiInterface
     */
    tABLEJCCTRLUserCodeGet(userCode: string, options?: AxiosRequestConfig): AxiosPromise<TABLEJCCTRL>;

}

/**
 * TABLEJCCTRLApi - object-oriented interface
 * @export
 * @class TABLEJCCTRLApi
 * @extends {BaseAPI}
 */
export class TABLEJCCTRLApi extends BaseAPI implements TABLEJCCTRLApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEJCCTRLApi
     */
    public tABLEJCCTRLGet(options?: AxiosRequestConfig) {
        return TABLEJCCTRLApiFp(this.configuration).tABLEJCCTRLGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} userCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEJCCTRLApi
     */
    public tABLEJCCTRLUserCodeGet(userCode: string, options?: AxiosRequestConfig) {
        return TABLEJCCTRLApiFp(this.configuration).tABLEJCCTRLUserCodeGet(userCode, options).then((request) => request(this.axios, this.basePath));
    }
}
