/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PagedTABLEFAMEMO } from '../models';
// @ts-ignore
import { TABLEFAMEMO } from '../models';
/**
 * TABLEFAMEMOApi - axios parameter creator
 * @export
 */
export const TABLEFAMEMOApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEFAMEMOGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/TABLE_FAMEMO`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} memoID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEFAMEMOMemoIDGet: async (memoID: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'memoID' is not null or undefined
            assertParamExists('tABLEFAMEMOMemoIDGet', 'memoID', memoID)
            const localVarPath = `/TABLE_FAMEMO('{MemoID}')`
                .replace(`{${"MemoID"}}`, encodeURIComponent(String(memoID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TABLEFAMEMOApi - functional programming interface
 * @export
 */
export const TABLEFAMEMOApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TABLEFAMEMOApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEFAMEMOGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedTABLEFAMEMO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEFAMEMOGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} memoID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tABLEFAMEMOMemoIDGet(memoID: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TABLEFAMEMO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tABLEFAMEMOMemoIDGet(memoID, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TABLEFAMEMOApi - factory interface
 * @export
 */
export const TABLEFAMEMOApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TABLEFAMEMOApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEFAMEMOGet(options?: any): AxiosPromise<PagedTABLEFAMEMO> {
            return localVarFp.tABLEFAMEMOGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} memoID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tABLEFAMEMOMemoIDGet(memoID: number, options?: any): AxiosPromise<TABLEFAMEMO> {
            return localVarFp.tABLEFAMEMOMemoIDGet(memoID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TABLEFAMEMOApi - interface
 * @export
 * @interface TABLEFAMEMOApi
 */
export interface TABLEFAMEMOApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEFAMEMOApiInterface
     */
    tABLEFAMEMOGet(options?: AxiosRequestConfig): AxiosPromise<PagedTABLEFAMEMO>;

    /**
     * 
     * @param {number} memoID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEFAMEMOApiInterface
     */
    tABLEFAMEMOMemoIDGet(memoID: number, options?: AxiosRequestConfig): AxiosPromise<TABLEFAMEMO>;

}

/**
 * TABLEFAMEMOApi - object-oriented interface
 * @export
 * @class TABLEFAMEMOApi
 * @extends {BaseAPI}
 */
export class TABLEFAMEMOApi extends BaseAPI implements TABLEFAMEMOApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEFAMEMOApi
     */
    public tABLEFAMEMOGet(options?: AxiosRequestConfig) {
        return TABLEFAMEMOApiFp(this.configuration).tABLEFAMEMOGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} memoID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TABLEFAMEMOApi
     */
    public tABLEFAMEMOMemoIDGet(memoID: number, options?: AxiosRequestConfig) {
        return TABLEFAMEMOApiFp(this.configuration).tABLEFAMEMOMemoIDGet(memoID, options).then((request) => request(this.axios, this.basePath));
    }
}
