/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CBRuleDissection } from './cbrule-dissection';

/**
 * 
 * @export
 * @interface CBRule
 */
export interface CBRule {
    /**
     * 
     * @type {number}
     * @memberof CBRule
     */
    'RuleID'?: number;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'BankAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'Match1'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'Match2'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'Match3'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'Match4'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CBRule
     */
    'ExactMatch1'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CBRule
     */
    'ExactMatch2'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CBRule
     */
    'ExactMatch3'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CBRule
     */
    'ExactMatch4'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'RuleType'?: CBRuleRuleTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'CustomerCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'CreditorCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'TransferCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'LastUsed'?: string;
    /**
     * 
     * @type {number}
     * @memberof CBRule
     */
    'MatchAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    'RegimeCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof CBRule
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {Array<CBRuleDissection>}
     * @memberof CBRule
     */
    'Dissection'?: Array<CBRuleDissection>;
    /**
     * 
     * @type {number}
     * @memberof CBRule
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof CBRule
     */
    '@odata.etag'?: string;
}

export const CBRuleRuleTypeEnum = {
    Withdrawal: 'Withdrawal',
    Deposit: 'Deposit',
    Transfer: 'Transfer',
    Receipt: 'Receipt',
    Payment: 'Payment',
    CashPurchase: 'Cash Purchase'
} as const;

export type CBRuleRuleTypeEnum = typeof CBRuleRuleTypeEnum[keyof typeof CBRuleRuleTypeEnum];


