/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GLBatchLine } from './glbatch-line';

/**
 * 
 * @export
 * @interface GLBatch
 */
export interface GLBatch {
    /**
     * 
     * @type {number}
     * @memberof GLBatch
     */
    'BatchID'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLBatch
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'SourceModule'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'Details'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'Description'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'BatchClass'?: GLBatchBatchClassEnum;
    /**
     * 
     * @type {number}
     * @memberof GLBatch
     */
    'Debits'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLBatch
     */
    'Credits'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLBatch
     */
    'Total'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'Error'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'PostStatus'?: GLBatchPostStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'CompanyCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof GLBatch
     */
    'SourceID'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof GLBatch
     */
    'ParentID'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    'SourceCurrencyCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof GLBatch
     */
    'ExchangeRateIE'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLBatch
     */
    'ExchangeRateALC'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLBatch
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {Array<GLBatchLine>}
     * @memberof GLBatch
     */
    'Line'?: Array<GLBatchLine>;
    /**
     * 
     * @type {number}
     * @memberof GLBatch
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLBatch
     */
    'SourceBatchID'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLBatch
     */
    '@odata.etag'?: string;
}

export const GLBatchBatchClassEnum = {
    GlBatch: 'GL Batch',
    ModuleBatch: 'Module Batch',
    ReversingJournal: 'Reversing Journal',
    StandingJournal: 'Standing Journal',
    TemplateBatch: 'Template Batch',
    ReversingOut: 'Reversing Out',
    Imported: 'Imported'
} as const;

export type GLBatchBatchClassEnum = typeof GLBatchBatchClassEnum[keyof typeof GLBatchBatchClassEnum];
export const GLBatchPostStatusEnum = {
    Unposted: 'Unposted',
    Posted: 'Posted',
    Deleted: 'Deleted'
} as const;

export type GLBatchPostStatusEnum = typeof GLBatchPostStatusEnum[keyof typeof GLBatchPostStatusEnum];


