/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GLSudsidiary
 */
export interface GLSudsidiary {
    /**
     * 
     * @type {number}
     * @memberof GLSudsidiary
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLSudsidiary
     */
    'CompanyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLSudsidiary
     */
    'CompanyName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GLSudsidiary
     */
    'ImportSource'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GLSudsidiary
     */
    'ImportDestination'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GLSudsidiary
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GLSudsidiary
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLSudsidiary
     */
    '@odata.etag'?: string;
}

