/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JCJobEstimate
 */
export interface JCJobEstimate {
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'EstimateLineType'?: JCJobEstimateEstimateLineTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'CostCentreCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'ComponentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'SalesGroupCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'QuantityEstimated'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'Description'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'Unit'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'UnitCostPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'ExtendedCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'UnitSellPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'DiscountPercentage'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'ExtendedSell'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'UnitSellPriceBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'ExtendedSellBs'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'Custom2'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'SellCurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'RateType'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'ExchangeRate'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'ComponentName'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'CostCentreName'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'MarkupPercentage'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'MarginPercentage'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'Reference'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'LineID'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof JCJobEstimate
     */
    'LineBreak'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JCJobEstimate
     */
    'LineSpace'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCJobEstimate
     */
    'LineNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCJobEstimate
     */
    '@odata.etag'?: string;
}

export const JCJobEstimateEstimateLineTypeEnum = {
    Time: 'Time',
    Material: 'Material',
    Disbursement: 'Disbursement',
    Narrative: 'Narrative'
} as const;

export type JCJobEstimateEstimateLineTypeEnum = typeof JCJobEstimateEstimateLineTypeEnum[keyof typeof JCJobEstimateEstimateLineTypeEnum];


