/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TABLECBAUDISS } from './tablecbaudiss';

/**
 * 
 * @export
 * @interface PagedTABLECBAUDISS
 */
export interface PagedTABLECBAUDISS {
    /**
     * 
     * @type {string}
     * @memberof PagedTABLECBAUDISS
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLECBAUDISS
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<TABLECBAUDISS>}
     * @memberof PagedTABLECBAUDISS
     */
    'value'?: Array<TABLECBAUDISS>;
}

