/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TABLECOMOCAT1 } from './tablecomocat1';

/**
 * 
 * @export
 * @interface PagedTABLECOMOCAT1
 */
export interface PagedTABLECOMOCAT1 {
    /**
     * 
     * @type {string}
     * @memberof PagedTABLECOMOCAT1
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLECOMOCAT1
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<TABLECOMOCAT1>}
     * @memberof PagedTABLECOMOCAT1
     */
    'value'?: Array<TABLECOMOCAT1>;
}

