/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { POOrderLine } from './poorder-line';
// May contain unused imports in some cases
// @ts-ignore
import { POOrderLink } from './poorder-link';

/**
 * 
 * @export
 * @interface POOrder
 */
export interface POOrder {
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'PrintStatus'?: POOrderPrintStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DateRequired'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DefaultExpenseCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'InternalReference'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'AuthorisationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'QuotationReference'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DeliveryAddress1'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DeliveryAddress2'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DeliveryAddress3'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DeliveryAddress4'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DeliveryAddress5'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DeliveryCountryCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DeliveryPostCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'Password'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'CreditorCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'DocumentID'?: number;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DocumentType'?: POOrderDocumentTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DocumentNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DefaultJobCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DefaultJCTransactionType'?: POOrderDefaultJCTransactionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DefaultCostCentreCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'OrderedAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'OrderedGST'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'QuoteGross'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'QuoteGrossBs'?: number;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DefaultComponentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DefaultLocationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DocumentClass'?: POOrderDocumentClassEnum;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DeliveryCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'PostStatus'?: POOrderPostStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DocumentDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'SourceID'?: number;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'SourceModule'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'Category1'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'Category2'?: string;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'ContactID'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'QuantityOrdered'?: number;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'Custom2'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DocumentClassNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'TotalWeight'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'TotalVolume'?: number;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof POOrder
     */
    'ContactEmail'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'ReceiptedAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'InvoicedAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'OrderedAmountBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'OrderedGstBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'ReceiptedAmountBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'InvoicedAmountBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'QuantityReceipted'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'QuantityInvoiced'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'QuantityShipped'?: number;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'ValuationDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'QuantityPendingInvoice'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'PendingInvoiceAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'PendingInvoiceAmountBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'ShippedAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'ShippedAmountBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'QuantityOutstandingReceipt'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'QuantityOutstandingInvoice'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'OutstandingAmountReceipt'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'OutstandingAmountReceiptBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'OutstandingAmountInvoice'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'OutstandingAmountInvoiceBs'?: number;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'BaseCurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'RateType'?: string;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'ExchangeRate'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof POOrder
     */
    'FixedRate'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'FxDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'RegimeCode'?: string;
    /**
     * 
     * @type {Array<POOrderLine>}
     * @memberof POOrder
     */
    'Line'?: Array<POOrderLine>;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof POOrder
     */
    'SourceDocumentID'?: number;
    /**
     * 
     * @type {Array<POOrderLink>}
     * @memberof POOrder
     */
    'Link'?: Array<POOrderLink>;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'AccountFile'?: string;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    'AccountCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof POOrder
     */
    'AllowManualNumbering'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof POOrder
     */
    '@odata.etag'?: string;
}

export const POOrderPrintStatusEnum = {
    Unprinted: 'Unprinted',
    Printed: 'Printed'
} as const;

export type POOrderPrintStatusEnum = typeof POOrderPrintStatusEnum[keyof typeof POOrderPrintStatusEnum];
export const POOrderDocumentTypeEnum = {
    Normal: 'Normal',
    Historic: 'Historic'
} as const;

export type POOrderDocumentTypeEnum = typeof POOrderDocumentTypeEnum[keyof typeof POOrderDocumentTypeEnum];
export const POOrderDefaultJCTransactionTypeEnum = {
    Time: 'Time',
    Material: 'Material',
    Disbursement: 'Disbursement',
    Narrative: 'Narrative'
} as const;

export type POOrderDefaultJCTransactionTypeEnum = typeof POOrderDefaultJCTransactionTypeEnum[keyof typeof POOrderDefaultJCTransactionTypeEnum];
export const POOrderDocumentClassEnum = {
    Order: 'Order',
    Quotation: 'Quotation',
    StandingOrder: 'Standing Order'
} as const;

export type POOrderDocumentClassEnum = typeof POOrderDocumentClassEnum[keyof typeof POOrderDocumentClassEnum];
export const POOrderPostStatusEnum = {
    Unprocessed: 'Unprocessed',
    Open: 'Open',
    Processed: 'Processed',
    Deleted: 'Deleted'
} as const;

export type POOrderPostStatusEnum = typeof POOrderPostStatusEnum[keyof typeof POOrderPostStatusEnum];


