/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEICSELL
 */
export interface TABLEICSELL {
    /**
     * 
     * @type {number}
     * @memberof TABLEICSELL
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICSELL
     */
    'PriceCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICSELL
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICSELL
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICSELL
     */
    'Price'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICSELL
     */
    'Markup'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICSELL
     */
    'RecordRevision'?: number;
}

