/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEARCONTCT
 */
export interface TABLEARCONTCT {
    /**
     * 
     * @type {number}
     * @memberof TABLEARCONTCT
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCONTCT
     */
    'ContactID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'CustomerCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'Role'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'Category1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'Category2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'Custom2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'Title'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'FirstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'MiddleName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'LastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'Suffix'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'PhoneNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'FaxNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'MobileNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'EmailAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'FirstNameLastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'LastNameFirstName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEARCONTCT
     */
    'IsPrimary'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEARCONTCT
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCONTCT
     */
    'LineNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCONTCT
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCONTCT
     */
    'FullName'?: string;
}

