/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEFAWORD
 */
export interface TABLEFAWORD {
    /**
     * 
     * @type {number}
     * @memberof TABLEFAWORD
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEFAWORD
     */
    'Word'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEFAWORD
     */
    'AssetCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEFAWORD
     */
    'Count'?: number;
}

