/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLECOCUSTOM
 */
export interface TABLECOCUSTOM {
    /**
     * 
     * @type {number}
     * @memberof TABLECOCUSTOM
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCUSTOM
     */
    'DatasetName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCUSTOM
     */
    'FieldName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCUSTOM
     */
    'UserCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCUSTOM
     */
    'ColumnNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCUSTOM
     */
    'DisplayLabel'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLECOCUSTOM
     */
    'Total'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCUSTOM
     */
    'FieldWidth'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCUSTOM
     */
    'LabelWidth'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCUSTOM
     */
    'Row'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLECOCUSTOM
     */
    'Visible'?: boolean;
}

