/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEICLINK
 */
export interface TABLEICLINK {
    /**
     * 
     * @type {number}
     * @memberof TABLEICLINK
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICLINK
     */
    'LinkID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'AccountFile'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'AccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'Category1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'Category2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'LinkType'?: TABLEICLINKLinkTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'FilePath'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICLINK
     */
    'LineNo'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICLINK
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICLINK
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICLINK
     */
    'RecordRevision'?: number;
}

export const TABLEICLINKLinkTypeEnum = {
    File: 'File',
    Web: 'Web'
} as const;

export type TABLEICLINKLinkTypeEnum = typeof TABLEICLINKLinkTypeEnum[keyof typeof TABLEICLINKLinkTypeEnum];


