/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLECBREVAL
 */
export interface TABLECBREVAL {
    /**
     * 
     * @type {number}
     * @memberof TABLECBREVAL
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECBREVAL
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECBREVAL
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECBREVAL
     */
    'RateType'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECBREVAL
     */
    'ValuationDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLECBREVAL
     */
    'ExchangeRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECBREVAL
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECBREVAL
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECBREVAL
     */
    'PeriodNo'?: number;
}

