/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEARADDR
 */
export interface TABLEARADDR {
    /**
     * 
     * @type {number}
     * @memberof TABLEARADDR
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARADDR
     */
    'CustomerCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARADDR
     */
    'DeliveryCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARADDR
     */
    'DeliveryCountryCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARADDR
     */
    'DeliveryAddress1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARADDR
     */
    'DeliveryAddress2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARADDR
     */
    'DeliveryAddress3'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARADDR
     */
    'DeliveryAddress4'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARADDR
     */
    'DeliveryAddress5'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARADDR
     */
    'DeliveryPostCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEARADDR
     */
    'Latitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARADDR
     */
    'Longitude'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARADDR
     */
    'ShipperCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARADDR
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARADDR
     */
    'Custom2'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEARADDR
     */
    'AddressNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARADDR
     */
    'RecordRevision'?: number;
}

