/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 5.0.11.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEARANLBAL
 */
export interface TABLEARANLBAL {
    /**
     * 
     * @type {number}
     * @memberof TABLEARANLBAL
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARANLBAL
     */
    'AnalysisCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEARANLBAL
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARANLBAL
     */
    'Budget'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARANLBAL
     */
    'PeriodActivity'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARANLBAL
     */
    'PeriodOpeningBalance'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARANLBAL
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARANLBAL
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARANLBAL
     */
    'PeriodNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARANLBAL
     */
    'PeriodClosingBalance'?: number;
}

